### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by silviuXgaming**

### CODE REVIEW

**Review by aandrew-me — COMMENTED** [review]
I don't see any difference

**Comment by silviuXgaming** [comment]
> I don't see any difference

Not now, later 😬

**Comment by aandrew-me** [comment]
Create a request once everything is ready

**Comment by silviuXgaming** [comment]
> Create a request once everything is ready

perfect, tks

**Comment by HyperAlch** [comment]
I would advice you delete this pull request. His whole GitHub is fake. He goes to a bunch of different projects and spams them with pull requests that add a line to the README or makes a fake change.

**Comment by HyperAlch** [comment]
1: Learn English
2: Shut your mouth, people like you make me sick. You take advantage of @aandrew-me and their hard work for your own selfish gain. I've already reported your account. If you want to impress an employer, earn it. Don't make fake pull requests so you can be listed as a contributor.

**Comment by silviuXgaming** [comment]
> 1: Learn English 2: Shut your mouth, people like you make me sick. You take advantage of @aandrew-me and their hard work for your own selfish gain. I've already reported your account. If you want to impress an employer, earn it. Don't make fake pull requests so you can be listed as a contributor.

1.I did the pull see how working, nothing else, and 2 ...go take your pills you have big problems ...3. I lose my time :d

**Comment by HyperAlch** [comment]
If you did it to "see how it works" why are you doing it to other projects?

Also you originally told @aandrew-me that you would update the pull request later remember? Back in November of 2023? Of wait, you just deleted that message to cover your tracks. 

image

Very weird how the message @aandrew-me replied to has magically gone missing. It's almost like there is a missing message between those 2 messages in the screenshot.

**Comment by silviuXgaming** [comment]
> If you did it to "see how it works" why are you doing it to other projects?
> 
> Also you originally told @aandrew-me that you would update the pull request later remember? Back in November of 2023? Oh wait, you just deleted that message to cover your tracks.
> 
> image
> 
> Very weird how the message @aandrew-me replied to has magically gone missing. It's almost like there is a missing message between those 2 messages in the screenshot.

kid you very lost :d :))

**Comment by HyperAlch** [comment]
### Imagine me finding another repo you have tried to spam....

image

I could go find more, but I think @aandrew-me has all the evidence he needs to delete this pull request and report you. Good luck.

**Comment by silviuXgaming** [comment]
@HyperAlch 
Qtile is better than Hyprland
not "hyperland"  :))

**Comment by silviuXgaming** [comment]
@HyperAlch is Arch btw
Not "Alch" :))

**Comment by aandrew-me** [comment]
I cant delete a merge request, I can only close it

**Comment by HyperAlch** [comment]
@aandrew-me 

That's fine. Close, delete, either way I just wanted to give you a heads up on this guy. Thanks for your hard work man, I appreciate you.

**Pull request closed without merging**
