### PR TITLE
Patch 2

### PR DESCRIPTION
**Pull request by 1RaY-1**
So I made 2 changes: 
1: Remove unwanted 'to' text in install script (forgot to do this before)
2: Add installer script for Windows:
I wrote this script in PowerShell and tested it on 2 different Windows10 machines and it worked. I also commented the code and basically what it does is to download executable for needed processor architecture, move it to ```C:\Program Files\TGPT\``` directory and add this directory to the PATH. It also checks if user has choco or scoop installed, so there is no need to do this all manually, but choco for example (and probably scoop too) installs a bit older release of tgpt (1.6.4 in my case).

To download and execute the script, the user would have to open powershell as admin and run this: ```wget https://raw.githubusercontent.com/aandrew-me/tgpt/main/install-win.ps1 -OutFile "$PWD\install-win.ps1";  .\install-win.ps1```

And if user receives "execution of scripts is disabled on this system" error, then in admin powershell he has to run: ```Set-ExecutionPolicy RemoteSigned``` (this will also allow to add the executable's directory to path using profiles) and then run the previous command again

What is left to do is to edit README.md

### CODE REVIEW

**Comment by 1RaY-1** [comment]
But maybe better still use ```Invoke-WebRequest https://raw.githubusercontent.com/aandrew-me/tgpt/main/install-win.ps1 -OutFile "$PWD\install-win.ps1";  .\install-win.ps1```, just in case if user installed wget.exe

**Comment by 1RaY-1** [comment]
And btw I think I did not mention that after adding tgpt.exe to PATH using profile, it can only be ran with Powershell (I mean by just typing ```tgpt``` from random directory), and can't be ran with cmd, because this profile is a ```.ps1``` file.

Maybe there is an option to add it to path which can be also accessed with cmd, but I tried to make it in the safest way.

**Comment by aandrew-me** [comment]
Ok let me see. Also is it necessary to check for `scoop` and `choco` when using the script. People who have them would use them in the first place. Removing it will give people another way to install the program. If for example they don't want to install with `choco` or `scoop` then they can use this script

**Comment by 1RaY-1** [comment]
You are right, what we can do is remove lines 14-23 (but let the ```Check-Command``` function because it's still used in the script)

The script installed it once with ```choco``` on 1 machine, and after removing the tgpt from ```Program Files``` dir (after script installed it manually), I could run the older version of tgpt using cli, but couldn't remove it using ```choco uninstall tgpt```, it sayd something like *Program doesn't exist*


Never heard of setx, will search in internet about it.

**Comment by aandrew-me** [comment]
> You are right, what we can do is remove lines 14-23 (but let the `Check-Command` function because it's still used in the script)
> 
> The script installed it once with `choco` on 1 machine, and after removing the tgpt from `Program Files` dir (after script installed it manually), I could run the older version of tgpt using cli, but couldn't remove it using `choco uninstall tgpt`, it sayd something like _Program doesn't exist_
> 
> Never heard of setx, will search in internet about it.

Yeah, also I don't think users run `choco` or `scoop` in admin shell. 

When I ran the script, it detected choco and installed with choco, then when I tried uninstalling with choco I got permission errors

**Comment by 1RaY-1** [comment]
Ok, I didn't know about admin permissions with choco, my bad.

The sing is that I actually know more about Linux and bash, but because I sometimes use Windows, and I know how to make cli scripts, tried to make an installation scripts with all the options of installing tgpt

**Comment by aandrew-me** [comment]
> Ok, I didn't know about admin permissions with choco, my bad.
> 
> The sing is that I actually know more about Linux and bash, but because I sometimes use Windows, and I know how to make cli scripts, tried to make an installation script with all the options of installing tgpt
> 
> When I was testing the script, the only thing I forgot about to see, is how to uninstall it after choco or scoop

Yeah that's fine! I have Windows in VM just to test things

**Comment by 1RaY-1** [comment]
Speaking of setx, what we can do is try this ```setx /M PATH "$Env:PATH;C:\Program Files\TGPT"```

**Comment by 1RaY-1** [comment]
Do you want me to explain what this does?

**Comment by aandrew-me** [comment]
No, should this be replaced or that line will be added to it

**Comment by 1RaY-1** [comment]
Well if ```setx /M PATH "$Env:PATH;C:\Program Files\TGPT"``` works on VM, and we have our path working on both  cmd and powershell

I suppose variable $add_to_profile is useless, so remove it, this ```$add_to_profile | Out-File $profile``` we would rewrite with ```setx /M PATH "$Env:PATH;C:\Program Files\TGPT"```, and we would also remove the first if-else

**Comment by aandrew-me** [comment]
It would be better if you do it, or just paste the code here and I will put it

**Comment by 1RaY-1** [comment]
I just tried it and it apparently worked, now I can run it either with powershell or cmd (but after restarting terminal).
I still ran it with powershell as Admin, I don't think this will make any big differences.

Will upload here code so you can try it too, but wait a little cause it's in the VM

**Comment by 1RaY-1** [comment]
Try this, but make sure that tgpt wasn't installed with choco or scoop
```
# TGPT installer script for Windows OS

# If receiving error "execution of scripts is disabled on this system", open powershell as admin and type next command:
# Set-ExecutionPolicy RemoteSigned

#Requires -RunAsAdministrator
$ErrorActionPreference = "Stop"

function Check-Command($cmdname){
    return [bool](Get-Command -Name $cmdname -ErrorAction SilentlyContinue)
}


# Or download and install it from source
$target_dir = 'C:\Program Files\TGPT' # <-- here we wanna store our executable file
$prog_name = "tgpt.exe" # <-- this is how we wanna call our executable

# Check if system is AMD64 or I386
if ((Get-WmiObject win32_operatingsystem | select osarchitecture).osarchitecture -eq "64-bit"){
    write "Downloading executable for: 64-bit OS"
    Invoke-WebRequest -URI "https://github.com/aandrew-me/tgpt/releases/latest/download/tgpt-amd64.exe" -OutFile "$PWD\$prog_name"
}
else{
    write "Downloading executable for: 32-bit OS"
    Invoke-WebRequest -URI "https://github.com/aandrew-me/tgpt/releases/latest/download/tgpt-i386.exe" -OutFile "$PWD\$prog_name"
}

# Move executable to 'C:\Program Files\TGPT' folder

# (who knows, maybe someone has installed Windows on another partition)
if (!(Test-Path -Path 'C:\')) {
    write "C:\ Doesn't exist"
    exit
} 

write "Installing TGPT in C:\Program Files\"
Sleep 2
# Create 'TGPT' folder in needed directory
if (!(Test-Path -Path $target_dir)) {
    New-Item -ItemType Directory -Path $target_dir
}
# If tgpt is already installed, will overwrite it
if (Test-Path -Path $target_dir\$prog_name -PathType Leaf){
    Remove-Item $target_dir\$prog_name -force
}
Move-item -Path $PWD\$prog_name -destination $target_dir\$prog_name

# And add it to PATH
write "Adding TGPT to the PATH"
if (Check-Command -cmdname $prog_name){
    write "$prog_name is already in PATH"
}
else {
    setx /M PATH "`$Env:PATH;$target_dir"
}

write-host "Done! Terminal GPT is installed in '$target_dir\'."
#   Remove last dot from variable prog_name
$new = $prog_name.Substring(0, $prog_name.lastIndexOf('.'))
write-host "Now restart your terminal and run '$prog_name -h' or '$new -h' for help."
```

**Pull request merged**
