### PR TITLE
added new option 'web' to open url from tgpt and added feature: render latex code in browser in interactive mode

### PR DESCRIPTION
**Pull request by git-aniket**
I added this flag since I thought this was an easy way to solve the latex problem without going through the hassle of having to render images in the terminal.

### CODE REVIEW

**Comment by aandrew-me** [comment]
How does it address the latex issue?
Also you called the flag `webHookUrl`, but counterintuitively it doesn't take input any URL, rather opens chatgpt's page
Not making much sense to me

**Comment by git-aniket** [comment]
Hi Andrew, 
I have now added an option to include a URL for opening in the default browser. 

As you pointed out, the latex issue cannot be directly solved in the terminal. So I thought that if one requires additional features,  such as equations and math displayed, it's better to directly open it in the browser.  This can now be done from tgpt using the -web option.

**Comment by git-aniket** [comment]
New Feature added:
In the interactive mode, if the response contains latex characters, the code is rendered in a browser.

**Comment by aandrew-me** [comment]
I think the webhook and websearch is getting out of the scope of what this program is actually meant for

**Pull request closed without merging**
