### PR TITLE
Added GPT-4-mini, from duckduckgo\'s endpoint. Changed default user-agent to "Linux" too (we gotta contribute to making `linux`'s marketshare be bigger in the pie charts!)

### PR DESCRIPTION
**Pull request by xplshn**
Changes:
 - Added GPT-4-mini, from duckduckgo\'s endpoint. Changed default user-agent to "Linux" too (we gotta contribute to making `linux`'s marketshare be bigger in the pie charts!)
 
Screenshot:
image

Note: Duckduckgo currently hosts a lot of interesting and novel AI models, such as Claude's Haiku, LLaMA 70b, and etc, I would love to see those here. Also, unrelated; Would you be open to doing a major refactor of `tgpt` to avoid code repetition? And creating/using ./pkg/ccmd (which would be very similar to [a-utils/pkg/ccmd](https://github.com/xplshn/a-utils/blob/master/pkg/ccmd/ccmd.go))?.

I'd like to contribute to making `tgpt` smaller, readable and more useful, also, have you considered replacing bubbletea? Its a heavy dependency, and it isn't really justified for what is used here...

### CODE REVIEW

**Comment by xplshn** [comment]
NOTE: Currently prevMessages is not handled, I may not have time this week to work on this. (this means that, as-is, the `duckduckgo` provider is not usable with `-i` nor `-m`.)

**Comment by aandrew-me** [comment]
Great! I had done some refactoring which is still in the develop branch, it needs to be merged to main branch. 
Regarding bubbletea, if you have a better alternative for multiline mode, let me know

**Comment by xplshn** [comment]
I suggest this tUI library, its great. https://github.com/rivo/tview
image

**Comment by aandrew-me** [comment]
Okay I have merged the branch where I did some refactoring. Please resolve the conflicts and I can merge.

**Comment by aandrew-me** [comment]
I will check the lib

**Comment by xplshn** [comment]
Currently, the provider duckduckgo.go does not handle prevMessages, and I don't know how to fix that. So, using `tgpt -m` and `tgpt -i` is impossible. Could guide me with that..? You shouldn't merge this until I fix that.

**Comment by aandrew-me** [comment]
> Currently, the provider duckduckgo.go does not handle prevMessages, and I don't know how to fix that. So, using `tgpt -m` and `tgpt -i` is impossible. Could guide me with that..? You shouldn't merge this until I fix that.

Hmm I will take a look

**Comment by aandrew-me** [comment]
I resolved the conflicts and merged your changes into the develop branch, I will work on it there

**Comment by aandrew-me** [comment]
I have fixed the json parsing error. However I still hasn't found why it gives the following error
```
{
    "action": "error",
    "status": 400,
    "type": "ERR_INVALID_VQD"
}
```

**Comment by xplshn** [comment]
> I have fixed the json parsing error. However I still hasn't found why it gives the following error
> 
> ```
> {
>     "action": "error",
>     "status": 400,
>     "type": "ERR_INVALID_VQD"
> }
> ```

Good, I also got to that point, but couldn't figure out the rest

**Comment by aandrew-me** [comment]
I found the issue, fixed it in develop branch

**Pull request closed without merging**
